# Build Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15-browsers
    working_directory: ~/swingessentialsweb
    environment:
      - MASTER_BRANCH: master
      - DEV_BRANCH: dev
      - GH_EMAIL: boyle.p.joseph@gmail.com
      - GH_NAME: joebochill
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
        
      # Run Tests
      # - run: 
      #     name: Run Tests
      #     command: yarn test

      # Lint
      - run: 
          name: Lint
          command: yarn lint

      # Build
      - run: 
          name: Build
          command: |
            if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]; then
              yarn ga:prod
            fi 
            yarn build
      
      # Deploy to web
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]; then
              yarn deploy --prod
            fi 
            if [ $CIRCLE_BRANCH == $DEV_BRANCH ]; then
              yarn deploy --dev
            fi 