export const ROUTES = {
    HOME: '/',
    LOGIN: '/signin',
    FORGOT: '/forgot-password',
    PROS: '/our-pros',
    BLOG: '/19th-hole',
    TIPS: '/tip-of-the-month',
    LESSONS: '/lessons',
    ORDER: '/purchase',
    SUBMIT: '/redeem',
    PROFILE: '/profile',
    REGISTER: '/register',
    UNSUBSCRIBE: '/unsubscribe',
    RESET: '/reset',
    PRIVACY: '/legal/privacy',
    TERMS: '/legal/terms',
    ADMIN: '/admin',
};
