import Boyle from '../assets/images/pros/boyle.png';
import AJ from '../assets/images/banners/nelson.jpeg';

export const MockBios = [
    {
        id: '1',
        name: 'A.J. Nelson',
        title: 'Lead Instructor',
        bio:
            "It's a pleasure to meet you. My name is A.J. Nelson and I am a Class A Member of the PGA. My goal is to grow the game of golf, one player at a time.|:::|I have been working in the golf industry for 19 years and have given thousands of lessons. I earned a Masters Degree from the University of Maryland, College Park and have graduated from the PGA sponsored Professional Golf Management Program.|:::|My strengths lie in teaching, club fitting, and player development. I look forward to bringing you my expertise in golf and feel extremely privileged to have the opportunity to work with you.",
        image: AJ,
        imageSize: '130%',
    },
    {
        id: '2',
        name: 'Joseph Boyle',
        title: 'Associate Instructor',
        bio:
            'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.|:::|Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.',
        image: Boyle,
    },
];

export const MockBlogs = [
    {
        id: '55',
        date: '2020-04-26',
        title: 'What Are You Playing For?',
        body:
            'Recently, a few folks went out on the golf course to see if all their hard work and practice was paying off. I decided to follow them onto the golf course to see how they were doing. When one of the folks got into a bunker, I drove up and asked him where he thought he was aimed. I asked him to draw a line in the sand, left of target to help  with his aim. He looked at me and said, "I don\'t think you can do that, and isn\'t that against the rules?" I responded with, "It absolutely is, but what are you playing for today?" In summary, his goal was to get better, and he was out on the golf course with his friends who were also trying to improve their game. He hadn\'t practiced that much in the sand before, and he was limiting his progress by not taking advantage of opportunities to get better. |:::|Therefore, if you aren\'t competing in tournament golf, or playing for your regular $10 weekend Nassau, then use opportunities on the golf course to help make you a better player. It will pay off when you start to enter into tournaments or have a friendly wager against for your friends. ',
    },
    {
        id: '54',
        date: '2020-04-11',
        title: 'Importance of Identifying Injuries Before Instruction',
        body:
            "Injuries not only dictate what limitations a player may have physically, but they also should guide instructors on how to teach their students. If a player has had a hip replacement, and the player has limited hip mobility, the instructor may have to compensate when teaching their student, having them use more arms in their swing, or installing equipment updates to make golf easier and more fun for their players. Another example involves a player with a new knee replacement. For this player, turning on their left knee (lead knee) would be extremely painful. The instructor would likely exaggerate the flaring of their lead foot towards the target to relieve the stress put on the lead knee. If you have any injuries, please make sure that the instructors know any physical limitations, as it will guide them to get you swinging better in no-time! If you're an instructor, make sure to understand any limitations early in the teaching process. ",
    },
    {
        id: '53',
        date: '2020-03-10',
        title: 'Working With Wounded Warriors',
        body:
            'The highlight of my teaching career is working with our Wounded Warriors. Being able to take golf, and use it as a rehabilitation tools is a very unique and understated tool that many sports simply can\'t mirror. When working with wounded warriors, the teaching methodologies are tested and challenged. Instructors who can teach golfers with adaptive needs (mentally or physically) stand out as some of the best in the nation. For instance, when a golfer may not have the use of their trail leg, it becomes challenging to teach a foundation of the sport like "weight-shift". During my interactions with a similar student, he struggled to get the ball airborne and on line. We simply strengthened his grip, and had him put the ball further back in his stance. With a very strong grip, and the ball in the middle back of his stance, he didn\'t have to shift his weight, and his clubface was square at impact. He said he hit it further than when he had the use of both legs. Although I was grateful to help a wounded warrior, I learned that golf is much more than a sport, and can be used as a therapeutic tool in one\'s recovery. For all the wounded warriors out there, please visit www.SwingEssentials.com and use the coupon code "Warrior" for a free golf lesson. Thanks for your service.  ',
    },
    {
        id: '52',
        date: '2020-03-06',
        title: 'Guest Post from TBT',
        body:
            'Greetings Golfers,|:::|Spring is just around the corner and I hope you find yourselves Coronavirus free and ready to hit the links.  I would love to join you but unfortunately I have to take a break from golf. My body needed a tune-up and a few months ago I replaced both knees.  Last year my son showed me a video of myself at the driving range.  Damn, now there’s a walk of pain and look at the geezer trying to get in the car.  I asked my son how long he thought I’d been like this.  “Years”, he said, "and by the way, we’re all tired of your whining and waiting for you.”  After contemplating my quality of life I guessed it was time.  At the advice of my caddy and everyone else I know, I had  surgery this fall and I’m slowly getting back to normal.  Some people will do anything to keep golfing.   Note to self:  If you ever want to golf again get off the couch, back into rehab, and ditch the opioids. |:::|My friend Mortie called me yesterday to play golf this weekend. The last time I saw him I could hardly walk and I know I told Mortie I wouldn’t be golfing for quite awhile.  His memory is so much worse than mine, which does make me feel better.  I guess I could ride along with him in the cart but he’s too cheap to buy me a few beers so I’ll probably just stay home and watch golf.  My Lazy Boy is calling.  Where’s that remote.  Happy golfing and stay healthy.|:::|Oh, and send in your golf swing videos for a free golf lesson! www.SwingEssentials.com|:::|TBT (The Big Toe)',
    },
    {
        id: '51',
        date: '2020-02-21',
        title: 'Dialing in Your Wedges',
        body:
            'When dialing wedges, it\'s important to keep as many "constants" in your swing as possible. For instance, if a student can keep their stance width very narrow, grip the same, and tempo consistent, they will be much more precise with their short game. With borrowed methodologies from world-renowned instructors like Dave Pelz, a simple "clock" system will help most mid to high handicap golfers. For instance, imagine if a person\'s hands represent the hands of a clock. When the player addresses the golf ball, their hands will be at 6 o\'clock. If the golfer brings their hands in the back-swing to 7:00 (or just past your right knee), and keeps all the "constants" listed above the same, they can produce a very repeatable golf swing. If the player can then add a 9 o\'clock swing (hands level to the ground, lead arm across the chest), and a 10 o\'clock swing (full swing), then the player can have three repeatable golf swings with each wedge they have in their bag. This means the player can have nine to twelve repeatable distances within 145 yards.  This can drastically lower their golf swing and make golf a lot more fun. |:::|To make golf more fun, send in a video to Swing Essentials for a free golf lesson!',
    },
    {
        id: '50',
        date: '2019-12-29',
        title: 'How Incorrect Aiming Techniques Keep Instructors in Business',
        body:
            'Harvey Penick wrote a book entitled, "Harvey Penick\'s Little Red Book". In this book, he discusses taking "Dead Aim". In summary, "Dead Aim" is the process by which a student chooses a point to aim at, and then visualizes the swing towards that very specific target. However, students keep golf instructors busy with poor aim. Poor aim can cascade into very costly and frustrating swing motions that can plague golfers for years, and in some cases, decades. When you go hit a bucket of golf balls, ensure that you do at least two things before you start your first swing. First, line up two golf clubs on the ground. The first club you put down is your foot line. This will be the line you align your toes up to and it should point to the left of your target. The second club you place on the ground should be parallel and approximately 25 inches in front of the first club (depending on your club you are going to swing). This should point at your target. Secondly, make sure your shoulders are square to the foot line. If you want to save yourself a lot of errant shots, take "Dead Aim" and ensure that your toe and shoulder line, don\'t intersect with your swing/target line. Many of my students send in swing videos with poor alignment. If you don\'t know where you are aiming, you won\'t know where you are sending the golf ball. If you need some help, download our Swing Essentials Golf App for a free online golf lesson!',
    },
    {
        id: '49',
        date: '2019-10-18',
        title: 'Alignment',
        body:
            'Alignment. In short, if you are not pointed in the right direction, you are not going to play well. When practicing, focus on three facets of your alignment. First, ensure that your feet are lined up a bit left of target. If your feet are aligned towards your target, your swing path will be pointed to the right of your target. This is called the "Train-track Effect". Your feet need to be aligned to the left of the target so that your club and golf ball are lined up towards the target, much like a train-track. The feet are the left track, and your golf ball and golf club are the right track. Secondly, ensure that your hips are aligned with your feet. This keeps your core engaged and allows you to have a full turn. Lastly, make sure your shoulders are lined up with your hips and feet. If your shoulders are lined up left of your foot line, then even if you make a full shoulder turn, you won\'t be able to hit the inside of the golf ball.  This causes an over-the-top slice that will lead to other bad habits. When you keep your feet lined up with your hips and shoulders, you\'ll be hitting the golf ball much more consistent. Have fun on the golf course, and remember to use the Swing Essentials Golf App for your free virtual golf lesson!',
    },
    {
        id: '47',
        date: '2019-08-25',
        title: 'The Most Versatile Training Aid: The Towel',
        body:
            'A towel can the be the most versatile training aid in any golfer’s arsenal. A towel can quickly increase club head speed, improve touch on the putting green, or even promote crisp chip shots around the fringe. During your next practice session try these tips with a towel:|:::|1. When you’re on the driving range, place a towel between your lead bicep and your pectoral muscle. Keep it pinched throughout the golf shot. This arm/body connection easily increases club head speed for further drives and longer iron shots.|:::|2. As you chip around the practice green, place an unfolded towel an inch behind your golf ball. When you chip, make sure to miss your towel. This will promote a perfect chip, and you will stop hitting the dreadful “fat” chip shot.|:::|3. The next time you practice putting, grab three rolled up towels. Place the first one eight yards away, the second ten yards away, and the third twelve yards away. Try and hit ten golf balls between each towel. This will help you master your speed control on the greens.|:::|For more tips and videos, please visit www.SwingEssentials.com . Download our Golf App and get your free virtual lesson today! Have fun on the Golf Course.|:::|This golf tip was also featured on https://backswing.com/roundup/what-is-your-favorite-full-swing-training-aid/|:::|',
    },
    {
        id: '45',
        date: '2019-08-04',
        title: 'Slow Play: A Culture Change',
        body:
            'Most golf courses in America define slow play as a round lasting more than four hours and twenty minutes. Due to slow play, facilities suffer from lost revenue based purely on the ability to get their customers around eighteen holes in a reasonable time. This is a culture problem that needs both a long term and a short term response by the golf industry.|:::|In the short term, golf courses can make incremental changes. This includes putting a clock on the tee box every four holes. This constant reminder allows golfers to understand how long they are taking as they move around the golf course. Another way to encourage faster play is make the golf course itself a fun and friendly environment. Ensuring that the tee boxes have a recommended handicap associated with them allows folks to choose their tee boxes correctly. This allows the customers to play an appropriate yardage and have more fun.|:::|However, most pace of play issues are caused by inexperience and golfers not understanding etiquette. Facilities can institute policy ensuring that everyone who goes out on a golf course for their first time has played with one of their professionals. Blocking off tee sheets for beginners also can catch problems more “up-stream”, rather than dealing with the results. However, this takes time and staff to ensure culture change at a facility. The pace-of-play issue has to be a brand, not an issue. Golf courses should promote and be proud of their ability y to get folks around the golf course in a reasonable time.|:::|Lastly, good instructors can use playing lessons to help their golfers get around the golf course in a more expedient fashion. Get your golf lesson today by downloading our Swing Essentials Golf App. Good luck and have fun on the golf course.|:::|This golf blog post was also featured on |:::|https://backswing.com/roundup/what-are-your-thoughts-on-how-we-can-increase-the-pace-of-play-at-golf-courses/|:::|',
    },
    {
        id: '48',
        date: '2019-07-26',
        title: 'Work on things that make the game a bit easier',
        body:
            'If your practice sessions are few and far between, let’s work on things that make the game a bit easier. A simple set-up for every single club in your bag can improve consistency and make the game a lot less frustrating. Simply follow these four steps. First, grip the club and place your hands and the golf club above your head. Second, try to get your elbows to touch and let them fall onto your chest. Third, bend your knees and place your shoulders over your toes. Lastly, look at the sky and let the club fall to the ground. Where the club lands on the ground should show you where your golf ball should be. You’ll be perfectly set-up to the golf ball with every club. Try this drill and I know you’ll be shaving strokes off of your game, even with very little practice. Follow the video link and don’t forget to submit your golf swing today at www.SwingEssentials.com for your free virtual lesson. Have fun on the golf course!|:::|This golf tip was also featured at https://backswing.com/roundup/whats-the-most-effective-way-for-golfers-to-improve-if-they-dont-have-much-time-to-practice/',
    },
    {
        id: '46',
        date: '2019-07-13',
        title: 'Hitting Greens',
        body:
            "When approaching the green, most golfers don't take \"enough club\". For instance if they have a 150 yard shot into a green, many will hit a 7-iron instead of a 6-iron. This happens for many reasons but often the golfer has made an assumption that they will hit the golf ball in the center of the club face on every shot (I hit it great on the driving range!). According to John Daly and Fuzzy Zoeller, even the PGA tour players only hit a golf shot exactly how they want it about 75% of the time. Many don't play their yardages off of their full, perfect, driving range swing. Therefore, the next time you're going for the green, take an extra club with more yardage. You'll be having more birdie putts in no-time!|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '44',
        date: '2019-07-04',
        title: "No Time to Practice? We've Got Your Back",
        body:
            'If your practice sessions are few and far between, let’s work on things that make the game a bit easier. A simple set-up for every single club in your bag can improve consistency and make the game a lot less frustrating. Simply follow these four steps. First, grip the club and place your hands and the golf club above your head. Second, try to get your elbows to touch and let them fall onto your chest. Third, bend your knees and place your shoulders over your toes. Lastly, look at the sky and let the club fall to the ground. Where the club lands on the ground should show you where your golf ball should be. You’ll be perfectly set-up to the golf ball with every club. Try this drill and I know you’ll be shaving strokes off of your game, even with very little practice. Don’t forget to submit your golf swing today at www.SwingEssentials.com for your free virtual lesson. Have fun on the golf course!',
    },
    {
        id: '41',
        date: '2019-05-29',
        title: 'Should I Take a Golf Lesson, or Get Fit For Clubs?',
        body:
            "This is a great question. Many of my students often ask me if they should go get fit for new golf clubs. Normally, the answer is yes. Getting fit for golf clubs ensures that you have the right tool in your hand when you go out on the golf course. However, make sure you go see a PGA Professional first. If you get fit for clubs, the club fitter may not be a PGA certified professional and will likely not be giving you a golf lesson. This means that they will not be critiquing your stance, posture, and alignment. Things like how far away you're standing from the golf ball, or how tall you are at address can have significant implications on things like the club's lie angle. In other words, if you're hitting it dead left, it may not be your fault if your lie angle is two degrees higher because of a change in posture. In short, take a lesson and walk into your next fitting with the correct posture, grip and alignment. It is well worth the money and will greatly help you get better faster.|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '43',
        date: '2019-05-11',
        title: 'Make Chipping Easier',
        body:
            "Chipping is a terrific way to immediately lower your scores. 70 percent of golf shots are within 155 yards, and chipping makes up a significant amount of those. If we can make chipping easier, and the stroke smaller, your handicap will come down in no time. Here's an easy way to help...|:::|First, stand closer to the golf ball. In many of the videos that our students send in, we see students standing too far away from the golf ball. Let yourself get close to the golf ball and then use a larger putter stroke. Only instead of using a putter, use a pitching wedge or 7 iron. If you can make a smaller stroke, there is less room for error. We hope this helps, and good luck on the golf course!|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '42',
        date: '2019-05-03',
        title: 'Guest Post from TBT',
        body:
            'Greetings golfers!  Like me, you might still be talking about this years\' Masters and starting your "comeback".  I must say, it was one of the most exciting tournaments in a long time. It has motivated me to try and extricate myself from working on my man cave; “just drop the trowel and walk away from that new wall”.   While watching Tiger\'s comeback I got  two unexpected calls from Mortie and Hugo. They wanted to bet on the outcome. I thought it a sure bet; Tiger had let me down over the years and I figured he could only win on the senior tour.  Who knew?  I owe Hugo big time and I’ll be skipping my Vegas trip this year due to lack of funds; Mortie can wait.|:::|My overall critique of the Masters 2019:  not a 5 star, maybe a 4 1/2.  This is for showing only the leaders the last few hours (a pet peeve of mine).  I know people love to see a good comeback, especially Tiger, but I do like to see the other pro golfers too.  Like mere mortals, pros like Speith, Day, and Rory do have bad days and a triple bogey or two gives all us hackers hope.   And last,  but not least, I wish Jim Vance could speed things up and mute that God awful music when going to commercial next year.  In future Masters, stay away from the predictions from those talking heads on TV, my bookie knows a hell of a lot more than those guys.  |:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.',
    },
    {
        id: '40',
        date: '2019-04-19',
        title: 'Where to Leave the Golf Ball?',
        body:
            'Golf is very unique in that it can relate to numerous other sports. From footwork to hand-eye coordination, players can mimic feelings they feel in other athletic endeavors. In philosophy and strategy, other sports can help golfers lower their scores too. Let\'s take billiards. Many top pool players look at their shot and ask, "Where am I going to leave the cue ball?". When pitching, chipping, or putting, players should ask the same question, "Where should I leave my golf ball for the next shot?". So here\'s the answer to lower your scores: leave the golf ball where you will always have uphill putts. These are easier to make and will help you bring down your handicap. So the next time you\'re around the green, think like a pool player and ask, "Where do I want to leave this golf ball?".|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.',
    },
    {
        id: '39',
        date: '2019-03-29',
        title: 'Guest Post by TBT',
        body:
            'Ladies and Gents, |:::|Guess what day it is?  it\'s Friday, Spring cleaning day.  I was just in my garage looking for my set of clubs. Being OCD, I usually try to organize my garage and storerooms in the off season but this year the Lazy Boy won out.  Note to self:  you need to drop 20.  You think finding your clubs would be a no brainer,  "not in this house!”.  Over the years the boys have left a set or two, Mortie the CEO of fashion, loves to fly in and have a set waiting, I finally put my foot down at leaving his size 13 footjoys and purple stripe shirts; there are rules.  I’m really excited about my first day out and I have no doubt I’ll find my red golf bag or was it blue?  Doesn’t matter, I’ll grab one of my son’s 3 sets out of the hall closet on my way to the driving range. Damn, where was that driving range again?  Hang on, let me find the google machine and get an address plugged in.  Stay mobile and enjoy your golf season. |:::|TBT (The Big Toe)|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.',
    },
    {
        id: '38',
        date: '2019-03-14',
        title: 'Half Swings ',
        body:
            'One great drill that I have my students do is practice "half swings". This is accomplished by the golfer bringing the club half way back in time backswing, and then swinging the club half way to a full finish. This drill instills many good lessons. The first is balance as many folks get stuck on their back foot. The second is timing. The student learns that with smaller swings, timing is a necessity to get the ball airborne. Lastly, this drill helps tremendously with impact. Try warming up with this next time and watch your scores begin to drop.|:::|Don\'t forget to get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.',
    },
    {
        id: '37',
        date: '2019-02-17',
        title: 'Tee-Box Alignment',
        body:
            "Golf is a game of statistics. Therefore, let's set ourselves up for success off the tee-box. I see many of our students line up incorrectly off of the tee-box. |:::|Here's an easy tip; tee your ball up on the side with the most danger. For instance, if there is a water hazard, a line of bunkers, or an out-of-bounds area on the right side of the golf course, tee your ball up on the right side of the tee-box. |:::|This way, you'll be widening the fairway and aiming away from the danger, rather than lining it up on the left side of the tee-box and brining the right side of the golf course into play. Good luck on the golf course, and set yourself up for success off of the first tee!",
    },
    {
        id: '36',
        date: '2019-01-12',
        title: 'Relating to Other Sports',
        body:
            "Golf is a terrific sport because students can use lessons learned from other sports to improve their swings. For instance, let's examine a golfer's weight transfer. Many of my students have played baseball or softball, and throwing the a ball can drastically help golfers play better golf. When baseball or softball players throw the ball, they load up their weight on their back foot, and push off to get their weight to the front foot. The longer they want to throw the golf ball, the harder they push off their back foot. This is essential in golf as well. Loading your weight on the back foot and pushing off to make contact with the golf ball is a great way to become more consistent and longer with every club. |:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '34',
        date: '2018-12-11',
        title: 'How Should I Warm Up Before Teeing Off?',
        body:
            "When I'm on the practice tee giving lessons, I see so many golfers warming up incorrectly. If you want to ensure that you're ready to play your best golf, here's a four-step process to get you prepared. Number one, make sure to stretch. I've had students that play other sports, and when I ask them if they stretch before running, playing soccer, or baseball, they always say yes. However, they don't stretch for golf. Just like other sports, if you don't stretch, you are at risk for injury. |:::|After stretching warm up by hitting putts and short wedge shots. This allows you to find your impact zone and work on tempo. After you've hit a few wedge shots, proceed to the next step of correctly warming up. This involves hitting mid-to long irons. Now you should be analyzing your ball flight. Are you hitting it a little right, or a little left? Play that in your round today, as this is not \"Practice\" time, but \"Warm-up\" time. If you need to change something in your swing, set some time aside later to work on a swing fault. |:::|Lastly, the final club you hit on the range should be the one you take to the first tee. If hole #1 requires a driver off the tee, the driver should be the last shot you hit on the range before teeing it up. |:::|Complete this four-step process and you'll be ready to play your best golf, each and every time.|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '33',
        date: '2018-11-20',
        title: 'A Frost Delay, What is That?',
        body:
            "Now that the weather has turned cooler and we are officially moving into winter, golf courses usually move their first tee time of the day a few hours later. Here's why:|:::|When the temperature drops overnight and the dew freezes, ice forms. If players play on frozen grass, the grass will break off with the ice and die. This can lead to poor turf conditions, and patchy greens.|:::|If you're tee time was delayed this morning, just take solace in the fact that you're doing the golf course a favor by waiting until the ice melts.|:::|Also, don't forget to get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.|:::|",
    },
    {
        id: '35',
        date: '2018-11-18',
        title: 'Another Guest Post From TBT (Holiday Version)',
        body:
            "Greetings Golfers,|:::|It's my last weekend of golf before I hang up the FootJoys and close out the 2018 season.  The fall weather was spectacular where I live so I was able to play a few more rounds this year.  I love playing in the fall. There are definitely fewer golfers, and we played so fast I haven't seen a Marshall in 3 months.  Most of the serious golfers get frustrated losing their Pro V1's in the leaves and with higher scores, they just can't take it. They don't show up as often - it's hard for a Sandbagger to earn a buck. Losing balls has never been a problem for me and the Boys. We have a three second rule for all seasons. Lost ball, drop one and move on. Mortie still doesn't count lost balls though.  By the way, his cheating has escalated to a point we now call him Mr. President.  |:::|For all you would-be golfers, please take a lesson. May you have an enjoyable New Years golf experience.  |:::|Peace out and Happy Holidays. |:::|TBT|:::|Lastly, don't forget to get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '32',
        date: '2018-10-20',
        title: 'Where Is Your Belt Buckle Pointing?',
        body:
            "If you're missing your golf shots to the right (for right-handed golfers), stop and check to see where your belt buckle is pointing. I often see my students fail to get their weight onto the front foot, and when they make contact with the golf ball, all their weight is still on their back foot.|:::|A simple fix is to focus on where your belt buckle is pointed at the end of your golf swing. If you get your weight transferred correctly onto your front foot at the completion of your swing, your belt buckle should be pointing down the middle of the fairway. If your belt buckle is pointing to the right (for right-handed golfers), that's where you'll likely find your golf ball. |:::|It's simple! Point your belt buckle down the middle of the fairway when you're done with the golf swing for straighter shots. |:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.|:::|",
    },
    {
        id: '31',
        date: '2018-09-02',
        title: 'Guest Post From TBT',
        body:
            "I recently played a public golf course near my home that I've been driving by for years; twelve to be exact. I have the boys come out every fall for our annual golf weekend and needed to find a backup in case our regular courses are booked, getting too expensive or going out of business. These days I go weeks without food just to afford 18.  I'd heard for years this particular course sucked and was always up for sale.  My wife and my son, the golf pro, convinced me to get out of my LazyBoy and give it a try.|:::|Here's my theory:  the locals spread rumors about how bad certain public courses are to keep outsiders like me and the golf snobs out.  I don't think I'm a snob but I do tend to believe rumors (if it's on the internet it must be true). I should never listen to my friend Mortie, he's a total snob and a big fat liar and gossip.  Anyway, the course I ignored for years was a lot cheaper than courses in the area, fun to play, and best of all practically empty on a weekend!  Suggestion, don't believe your golf snob friends and give your local public courses a try. You may be surprised.  |:::|TBT (The Big Toe).|:::|P.S. |:::|Download that Swing Essentials Golf App! ",
    },
    {
        id: '30',
        date: '2018-08-29',
        title: 'Shoulder to Shoulder',
        body:
            "During your next practice session, check to see where your left shoulder (for right handed golfers) is moving as you begin your backswing. |:::|Is it moving north-to-south, or east-to-west?|:::|I see many folks move their forward shoulder down, when it should move towards the trailing shoulder. |:::|That said, when you are at the top of your backswing, your left shoulder should end up where your right shoulder was at address.|:::|It's a simple swing thought; get your lead shoulder over to your trailing shoulder during your backswing. Have fun and send in a video of your golf swing today. Download our app at www.swingessentials.com",
    },
    {
        id: '29',
        date: '2018-08-12',
        title: 'Chipping Yips: The Real Cause',
        body:
            "I often see my students struggling when chipping around the practice green. Many think that the reason is that they decelerate the club through the shot, or that their head comes up and they hit it thin. These are the results, not the causes.|:::|Most of the time, the real cause is that their left hand stops moving towards the target. When this happens, the right hand takes over and the student digs their club into the ground or hits it across the green.|:::|So the next time you have trouble with your chips, keep that left hand moving towards the target. If you're still having trouble, download our golf app and receive a free golf lesson with your download.",
    },
    {
        id: '28',
        date: '2018-07-23',
        title: 'Guest Post From TBT',
        body:
            "So, I've been watching the British Open this weekend; I mean 'The Open'. Question: Does network television spend too much airtime showing the pros line up their putts?  In the time it takes Tiger or Speith to putt I have enough time to renovate my Man Cave.   My golf buddy Morti, who watches a lot of golf, is now wearing out his size 12 Footjoys lining up putts around the greens.  I vote the PGA institute a new two stroke penalty for taking too long to line up a putt, call it the two commercial rule.  These days my LazyBoy isn't getting enough TV time and  I'm sure Bud Light is losing money.   Note to Golf channel - keep those  \"Live at the whatever tournament\" golf guys limited to minutes instead of hours of analysis. I'm sure I'd watch more golf if they'd show more of those blue laser lines after each shot and ALL the golfers, not just the leader board.  Just sayin'.  \"Hey Dear, Tiger is getting ready to putt again, can you help me with this drywall?\"|:::|Enjoy the Open.|:::|The Big Toe (TBT)|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '27',
        date: '2018-07-20',
        title: 'Putting Better: Left Hand Towards the Target',
        body:
            "Hey Pro, how can I start putting better?|:::|This is a question I often get from my students. To answer this, you need to understand how the back of the left hand (for right-handed golfers) works in the putting stroke. Many of my students miss their putts to the left, and the face of the putter ends up left of the target.|:::|The back of the left hand MUST go down the line and toward the hole. If the back of that left hand goes toward the hole, your ball will likely follow that route.|:::|Use the back of the left hand (for right handed golfers), and move it down the target line, and you'll be making more putts in no-time!|:::|-A.J. Nelson, PGA|:::|Still struggling? Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '25',
        date: '2018-06-27',
        title: 'The left wrist: the key to stop slicing...',
        body:
            "Where is the left wrist at the top of your swing?|:::|If it's bent, the ball is probably going right. |:::|The left wrist is a critical factor that wreaks havoc on players trying to keep their golf shots in the fairway, and it's one of the first things we examine in our golf analysis.|:::|Why does the left wrist (on a right-handed player) matter? Well, it starts at the grip. The left hand is in charge of the club-face (whether it's square or not), and the right hand is in charge of the path and bend in the shaft. Therefore the left wrist at the top of the back-swing, if bent, will stay bent on the way down and open the club-face throwing your golf ball to the right of the target-line. |:::|So if you're practicing alone, how do you check to see if your left wrist is straight at the top of your back-swing? |:::|It's simple, grab a credit card, drivers' license, or business card. Take one of these out of your wallet, and put it under your golf glove, under the Velcro. It should be laying flat from the backside of your hand, along your wrist, and partially on your forearm. When you swing,  if you feel a pinch at the top of your back-swing, you're bent at the top. |:::|The drill is to make sure you don't feel that pinch! Keep that left wrist straight.|:::|This \"instant-feedback\" drill will shave strokes off your game and have you hitting more fairways today!|:::|A.J. Nelson, PGA|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '26',
        date: '2018-06-15',
        title: 'Guest post from TBT',
        body:
            "Greetings Golfers|:::|I'm back baby, and my game is even better than I thought it would be. I'm here in Las Vegas and it's Par City.  Pay me Mortie and put me down for a birdie.  Eagle coming. These red tees are great eh?|:::|I took a long break from golf and as the years fly by I just wasn't feeling the love. I think it was a phase I went through or maybe my friends have yet to retire, I still don't do weekends. I guess I forgot that golf is good exercise and a great stress reliever. Get out there and smack something. My friend Hugo might smack the Marshall if he doesn't speed up that foursome in front of us soon. It's only the ninth hole, he'll never make it. Where's the Cart Girl?|:::|Enjoy your golf game wherever you are. Yo Eleven. |:::|Oh, and download the new Swing Essentials app!|:::|- TBT (The Big Toe)",
    },
    {
        id: '24',
        date: '2018-05-27',
        title: 'Hey Pro, how do I "read" greens?',
        body:
            "As we move full speed ahead into golf season, students at SwingEssentials frequently ask, \"Hey Pro, can I get some help reading greens?\"|:::|It's a challenging subject, but let's start with three basic questions. |:::|First, if it started raining (torrential downpour) while you were putting, where would the water flow on the green, and how fast? This allows the player to visually imagine slope, keeping in mind that the golf ball, would follow the imaginary water.|:::|Second, where is the sun? As we learned in grade school, grass needs water, nutrients, and most importantly, sunlight to grow. Therefore, the grass will bend towards the sun. If you're putting toward the sun, it will be a quicker putt than if you're putting against the sun. If you ever hear golfers ask, \"Are you putting with, or against the grain of the grass?\" you now know what they mean.|:::|Third, how fast is the green? When you arrive at a golf course, the most important stop on the way to the first tee should be the putting green. Many folks skip the practice green and head straight to the driving range. Make sure to test the greens before you head out to the first tee. That first putt may surprise you.|:::|Now you're ready! Go forth and master those greens, make more puts, and remember these three things; slope, grain, and speed.|:::|-A.J. Nelson, PGA|:::|Don't forget to receive your free online golf lesson. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '23',
        date: '2018-04-15',
        title: 'Grip Pressure',
        body:
            'I notice a lot of my students grip the club too tightly in their hands. When gripping the club, thing about holding a tube of toothpaste. For example, when gripping the club, don\'t hold it so hard that toothpaste would come out of the tube. |:::|With that mental note, what does holding the club lightly in your hands do for your swing? Very simply, it allows for more clubhead speed. The "whip" down at the bottom of your swing, near the impact position, will be hindered if you are gripping the club too tightly. |:::|So try it! |:::|When you\'re out on the golf course, or at the driving range, grip the club lightly and watch yourself gain a few yards on all your shots. |:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.',
    },
    {
        id: '22',
        date: '2018-03-11',
        title: 'Am I Standing Too Close, or Too Far Away From the Golf Ball?',
        body:
            "When I walk up and down the driving range, I tend to notice that many golfers don't stand the correct distance away from the golf ball. To put it simply, if these folks aren't setting up the right way, they've hindered their chances of success before they even swing the club. This can lead to the forming of bad habits, and a ton of frustration.|:::|So let's fix it.|:::|Start by standing straight up with your feet shoulder width apart. Put your hands on your thighs, bend your knees, bend at the waist and keep your back straight. When the tips of your fingers touch the tops of your knees, you have achieved the optimal golfing posture. Now staying in that posture, simply let your hands fall and grip the club. The ball should be where your clubface lies on the ground.  |:::|Now you're all set. We hope that this golf lesson will help you play better golf. Please visit swingessentials.com and sign up for your free lesson today.",
    },
    {
        id: '21',
        date: '2018-02-24',
        title: 'How to Start the Golf Season',
        body:
            'I\'ve had a few students ask me, "What is the best way to start out the golf season?" |:::|My answer is always the same, "Start with the PGA."|:::|Posture|:::|Grip |:::|Alignment|:::|Start the year on the right foot. Make sure your posture is tall with a straight back and your feet under your shoulders. Make sure your hands hang freely underneath your chin, and ensure that your knees are slightly bent. |:::|As for your grip, make sure you can always see two knuckles on your left hand (for right handed golfers) and that your right hand holds the club mostly in your fingers.|:::|When aligning yourself, make sure that your shoulders are aligned with your hips, knees and feet. Keep that ball lined up between your heart and left armpit (for right handed golfers). This keeps your impact zone the same throughout every shot.|:::|So the next time you take it to the course, make sure you begin with P. G. A. |:::|-A.J. Nelson, PGA|:::|Still having trouble on the golf course? Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.',
    },
    {
        id: '20',
        date: '2017-04-10',
        title: 'What Kind of Clubs Should I Buy?',
        body:
            "Talk about growth in the game! Across the nation, we are getting members emailing in with questions. Scott from Wisconsin asks,|:::|\"So I'm just getting into golf and have no idea what clubs I need to buy. Do you have any recommendations?\"|:::|Great Question Scott! Golf can be intimidating. However, buying golf clubs shouldn't be. If you're just getting into golf, drop by your local sporting goods store and pick up a starter set. Many now even come with a bag.|:::|Keep in mind that these clubs won't last for long. You should play with a starter set for about one to two seasons or until you feel a bit of consistency in your scores. Once you get hooked and really start playing, you'll have to start thinking about length, shaft flex, and grip.|:::|Therefore, here's a quick rundown of what you'll need to know once you \"graduate\" from your starter set|:::|1. Get the right shaft flex. The right shaft won't be too heavy. It may be steel or graphite, but you certainly don't want to swing something that's too heavy or too light. Common flexes are Light, Senior, Regular, Stiff, and Extra Stiff. A lot of tour players play Extra Stiff shafts, and my 85-year aunt plays Light shafts. You are probably in the middle.|:::|2. Get the right length. Length is important, but it doesn't depend on height. It has to do with how far the ball away is from you at the set up position. A rule of thumb is when you set up naturally to hit a shot, are you hitting it on the toe, or off of the heel of the club? If the heel, you need a shorter club. If on the toe, you need a little length.|:::|3. Grip is important. People have different size hands, so why should everyone have the same size grip? There is an easy test to see what type of grip you need. Simply hold the grip in your left hand (for right handed players). Does your ring finger touch the pad of your hand? If so, you've got the right grip! If it digs into the pad in your hand, it's too small. If it doesn't touch at all, you need a smaller grip.|:::|Now doesn't that seem easy? If you have any questions, please visit our website, or your local PGA member!|:::|Thanks and keep it in the short grass.|:::|A.J.|:::|Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '19',
        date: '2017-02-18',
        title: 'Great Turnout at the Dulles Golf Show',
        body:
            "Wow, that was unexpected!|:::|Swing Essentials headed out to the Dulles Golf Show last weekend, and to say that we were busy, well, that's an understatement! We had the pleasure of meeting and working (well, we don't really think of it as work per se)  with over 100 people!|:::|We had a blast helping people swing a club for the first time, getting tips on breaking 100, or simply knocking a few strokes off their game.|:::|And boy, we had everybody! We spent the weekend working with everyone and really having a great time.|:::|We hope you had a great time, and learned something in the process.|:::|We can't wait until next time but until then, we'll see you online, and in the future!|:::|Until then, get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '18',
        date: '2016-12-01',
        title: 'Golf on People',
        body:
            "Last month my wife quickly left town so the boys could fly in for our annual weekend golf and poker event.  What a weekend...the weather was perfect and golfing in the fall is my favorite time of year.  Our two foursomes  consisted of the \"Young Guns\" who keep us old guys competitive and the Grey Goats with our memories of better days.  Hugo tells the same old story that gets longer every year.  By the time he finished this year I was on my sixth beer.  He'd probably give it up if he could hear the comments but he's needed hearing aids for years.|:::|The Goat's foursome was one man short this year.  Mortie's so called new friend he invited last year was voted off the island for being an asshole.  Regardless of a man down, we posted our best score in years with 13 birdies and no bogies.   The wedge was working.  We always play best ball because that way we don't have to look for Mortie's orange balls when he slices out of bounds.  We were up before noon both days. Bets were made, the youths hurried off to the driving range, us old guys walked to the putting green.  We don't waste our good shots. This year's winnings kept us in poker money and paid for the Keg and moonshine. Next year we're upping the bet and will be upgrading to a premium brew.|:::|Regrettably, I haven't golfed  much this year and since my golf scores haven't improved I've decided to give it a break until January.  I'm hoping Mrs. Claus and the Elf son will surprise me with a new driver or putter this Christmas.   I've finally given up on the new clubs. My wife told me I should be happy with the two new sleeves of Pro V's that fell out of my golf bag.  No shirts, no shoes, no Pings.|:::|Golf on people and Happy Holidays.|:::|The Big Toe (TBT)",
    },
    {
        id: '17',
        date: '2016-10-01',
        title: 'Advocating for Junior Golf',
        body:
            'The key to junior golf is to get parents involved early and often. Leverage your generational experience.|:::|Parents determine not only how much fun the junior golfers have, but according to many psychologists and recent studies, dictate how successful kids can be in golf.|:::|Also, all indications are that junior golf is on the rise. According to Jake Turtel at Fortune 500 magazine, PGA Junior League Golf has expanded from 1,500 youth participants in 2012 to 8,900 in 2013. This indicates a 490% increase. In 2014, participation doubled (18,000 kids). With this trend, more juniors will be growing up and playing at your local golf courses.|:::|But how does the golf industry keep these juniors interested and around the game of golf? The answer is parental involvement. Parents, who are defined as being a part of Generation X, have a background that is conducive to advocating for junior golf. According to Jennifer McCallum, author of "Who is Generation X?" these parents have grown up in a world without social media, and yet have adapted to it - even invented it - exquisitely.|:::|Generation X, and their use of technology is the key to making sure this junior golf trend continues. New golf applications on a cell phone or tablet keeps kids not only involved, but also interested in the game. Golf is very unique in that it has "toys". If children play baseball, parents will often buy new shoes, bats, or gloves. But the golf industry allows so much more variety. From new hardware, like balls and clubs, to free golf apps on their cell phone to record scores and show trends, golf offers so much more. Also, kids love to see their swing on a screen next to Jordan Speith or Tiger Woods.|:::|Parents have to make sure that the environment for golf is inviting. The way to do this is through technology. The message is clear, to keep juniors in the game, simply have fun, be supportive, and incorporate all the new technological gadgets. Who knows, you may have more fun too.|:::|AJ|:::|You can also find this article published in the PGA Mid Atlantic Section magazine for November here:  https://issuu.com/mapga/docs/issue_2_spread',
    },
    {
        id: '16',
        date: '2016-09-09',
        title: 'Red Tees at Savannah Harbor Golf Club',
        body:
            "It's late August and I already surpassed last years golf outings. Hey, I'm a Senior and need to pace myself. I just returned from a 3-day golf vacation down south to the state of Georgia. Sounded nice although Savannah in August was a tad bit warm, like take your breath away warm and not a dry heat. What was I thinking, but who cares when you have tee times at Savannah Harbor Golf Club. Our threesome consisted of a Pro, my wife, and me, an old hacker. While I was watching the Pro and my wife waste their best shots on the golf range I loaded up the cart with ice water and out of the blue decided to join my wife and play from the red tees. It had nothing to do with slow play, it's just that I had never played from the red tees before. I thought I'd give it a try like the Arnie TV commercial, while we're still young.|:::|Wow, what a difference in play! I didn't realize how fun golf could be. I don't really need those Pings now. What an excellent golfer I have become, no more hacker comments from me. I consistently hit the fairway and was on in regulation the majority of the time; hand me my putter! I did hit a few bunkers because of the long drives but only lost one ball install of the usual ten. My attitude towards golf has been renewed. Now, if I can convince Mortie and Hugo to give it a try. If they see me drive the green it won't be hard. One final note before you give it a try, your score will likely stay the same. Note to self: Work on that putting game. You still need to get the ball in the hole. Happy Golfing.|:::|The Big Toe (TBT)",
    },
    {
        id: '15',
        date: '2016-07-06',
        title: 'What a Month!',
        body:
            "Wow, what a month! The students are really making a lot of progress. Let's take a look at our students accomplishments. They are certainly working hard.|:::|\"Thanks for the tune up. That first lesson set me up to win my first tournament of the year. 2016 Member-Guest Champions! Thank you for all of the help.\" - Tim|:::|That is impressive. We here at Swing Essentials are extremely excited to hear about everyone's success. Michael is also having a great start of the year.|:::|\"I've worked with Swing Essentials twice in the past month. I was shocked to see my video. Thank you very much for the analysis. I'm back on track and I just shot 37, 32. I dropped 5 birdies and had a great round. Golf is fun again!\" - Michael|:::|That's a lot of birdies! Thanks again Michael and congratulations.|:::|We hope to hear more successes stories. Keep them coming!|:::|A.J.|:::|You too can have this kind of success. Get your free virtual golf lesson today by downloading our Swing Essentials Golf App. Submit a video of your golf swing and a PGA Professional will provide you a free personalized golf swing analysis. Good luck and have fun on the golf course.",
    },
    {
        id: '14',
        date: '2016-07-05',
        title: 'Take a Loved One Golfing',
        body:
            "I've spent a lot of my time at the golf course with friends, Mortie excluded, and thought it was time to take a loved one golfing for a change. I'm sorry to say it's been awhile and for me, loved ones are hard to find these days. My son says I hate everybody, not true, but at my age I'll let that one slide.  Anyway, recently I asked my wife if she'd like to go golfing with me.  I was expecting a no, it's too hot and humid, but she said \"Sure, why not?\"  I then spent  most of the morning on a search and destroy mission to find her clubs in the basement storeroom.  I made sure all the mice were liberated from her golf bag and added a few items from my golf bag.  Most were gifts I got for Christmas last year still in their original packages.|:::|A vast majority of golfers hate to see a man and a woman golfer show up thinking they may be paired up with them and hope to get out first.  \"G-entleman O-nly L-adies F-orbidden\" is no longer applicable, get over it.  Besides, I know my wife is a better golfer than most of the hackers out there so I ignore the hostile looks and head for a beverage or two from the snack bar.  I must say, It's nice to have a loved one who knows the rules of golf and doesn't hold up play.  Unlike my friends, she doesn't cheat and is always in the fairway. I've decided the next time we play together I'll join her at the red tees while we're still young!  My score went down and I didn't have to stare at those ugly pro shop clothes throughout the day.  Take a loved one golfing and happy 4th of July.|:::|The Big Toe  (TBT)",
    },
    {
        id: '13',
        date: '2016-06-06',
        title: "Bear's Best",
        body:
            "We just returned from our annual Las Vegas golf and gambling extravaganza. As we get older one must choose whether  to golf with a hangover or hang by the pool.   It's now 50/50 and we we're down to a threesome the second day.  Sad but true; I think I just need more sleep and a better brand of alcohol but in Mortie's case, he's just a tightwad.  This year he didn't even get up for our 11:10 tee time. Why he comes to Vegas I'll never know.  I golfed Friday and Saturday because the bookies were still looking for me. I didn't play craps or blackjack after dropping 10 large and found a nice hiding place amongst the penny slots.  I was up $10.50 at one point, King me!|:::|It's nice to have connections with a Pro. We were lucky to get reservations at \"Bear's Best\" a Jack Nicklaus golf course, one of the finest in Nevada. What a beautiful course in the 90 degree desert, hey it's a dry heat!   We overlooked the 5 1/2 hours it took to play 18 because it was such an interesting course. Who let that foursome we followed play golf anyway, and where the hell did they disappear to after nine?  We could have used Hugo to speed up play but he didn't play after dropping a bundle the previous night.  Hotel security and the dealers weren't happy with him and in his mood slow play and a wave from a golf Marshal wouldn't have been pretty.|:::|After a a few bogies and a few cold ones my hunt for a restroom began.  Note to self: Stay away from the hotel \"Buffet (Boo-fey)\" before golf, when will I learn.  To my surprise a Porta-Potty appeared on the 8th hole just in time to save par,  it was quite a moment. Thank you Best Bear,  i'll be back.  Love the hat.   Mortie, next time find your own cab, and another thing you're off the island!|:::|The Big Toe (TBT)",
    },
    {
        id: '12',
        date: '2016-04-12',
        title: 'Wake Me Up',
        body:
            "So what's up with that horrible music they play during the Masters? Jesus, I'm already dozing.   I've been watching the Masters for years and I've got to tell you it's really starting to grind on me. Do you think CBS and those Atlanta Country Club geezers could throw some new tunes on while we're still alive?  How many of us fall asleep during the match?  I'd go for a little ZZ or Bruce to wake me up after the first hour.|:::|How come CBS starts the broadcast so late in the day, after talking about it for 2 hours before tee time?  Don't golfers usually tee off all day long and why do we have to watch only the leaders every year.  I don't miss Tiger whining all those years when he missed a shot.  I can only take so much of Jason Day's golf routine and Jordon Spieth's interviews; what about the other 89 qualified golfers? I miss Phil and we need more of Ernie Els footage.  6 putts from 3 feet!  Hey, I had 7  from 2 feet the other day;  Mortie won that hole.  Yes, Jim Nance and the God awful music will continue year after year and I'll continue to watch.  Some things never change.  Hand me the remote Dear, that f'ing Arnold Palmer and Kevin Nealon commercial is on again.|:::|TBT (The Big Toe).",
    },
    {
        id: '11',
        date: '2016-03-06',
        title: 'Stay Motivated My Friends',
        body:
            "I looked out my window this morning and can see my yard is going to need a lot of work this year. This is not good; I might have to tap into my golf fund.  Yes,  some people have golf funds. I started bi-weekly transfers a few years back to pay for my annual golf vacations and gambling debts.  If truth be told, it goes to buying more grass seed and weed killer.   Yesterday, rather than going to Lowe's or Home Depot I went directly to Expedia.com and booked a flight to Vegas.  Note to self, increase bi-weekly allotment; I'll need the early bird check-in and fares are still going up.|:::|Every Spring I try and get motivated after my son calls and asks \"How many times have you been out of the house this week?\"   Hey, I've been working on my Man Cave.  Usually after his call I vow to play more golf and get out more but usually fall short.|:::|I now have four sets of golf clubs in my storeroom collecting mildew.   Maybe I'll move them to the garage, somewhat closer to my local golf course.  When these storms blow over I might take a trip to the driving range, but I'll need to charge my car battery and clean out the trunk first.  Stay motivated my friends!|:::|TBT (The Big Toe)\r\n",
    },
    {
        id: '10',
        date: '2016-01-20',
        title: 'Happy New Year',
        body:
            "Christmas has come and gone.  I asked my wife a couple days after Christmas if all the gifts she ordered had arrived from Amazon.  She laughed and said, \"Yes, why do you ask?\" I told her that I expected at least a new golf shirt, periwinkle blue from me ma. She said that she had discussed giving golf presents with the family and it was unanimous, why bother.  I asked again to see if I heard her right;  I did lose my hearing aid in November.  She shook her head up and down and told me that I'd be better off going to Home Depot and buying a drill.  I'd be much happier drilling holes at home rather than trying to drill one on the green. The shock on my face must have looked like somebody died but I guess I deserved that comment;  I did complain about the putter she gave me last year. I called my son the next day and asked if it was true. He told me that they were all tired of me whining about my golf game, and as much as I play that I was lucky to break 100.  Forget about all the golf presents he said, get a life! Touche', maybe he had a point.  Golf  is supposed to be fun and for all the serious golfers, forget about the new Pings, take a lesson or two and keep your thoughts about your game to yourself. Who knows maybe next year you might get a bag of 6 inch tees to help your game.  Happy New Year.|:::|The Big Toe (TBT)",
    },
    {
        id: '9',
        date: '2015-12-16',
        title: 'Happy Holidays',
        body:
            "So every year I ask myself, \"what do I need for Christmas to help my golf game ?\" And every year my wife laughs and tells me to give it up. I do love the gift cards I sometimes get, even the ones for my local golf club. The double EE size 14 Foot Joys aren't working for me. I'm still wearing two pairs of sports socks hoping they shrink some day. Maybe I'll get a card from Dicks this year and won't have to settle for another purple striped shirt from the Pro Shop. I still have my eye on those Pings but when you only golf two or three times a year it's hard to justify. Maybe some new grips? I'll definitely get another new hat to cover up the comb over or maybe some of those yellow or orange golf balls. I do have new glasses so I should be able to find a ball or two next season. Depending on who throws a gift card my way, I might even take a lesson. Hell, maybe I'll see if I can use it to play golf. Happy Holidays.|:::|The Big Toe (TBT)",
    },
    {
        id: '8',
        date: '2015-11-17',
        title: 'End of Golf Season',
        body:
            "Damn, another golf season has come and gone.  I really didn't play as much golf as I wanted this year but May and October were my two best rounds, that's two out three total.  I hope to return in the Spring but might have to look into Yoga this winter. What the hell happened to me?  I've got to get off the Ben and Jerry's.|:::|The highlight of my season was I had Frankie take some videos of my swings and had them analyzed on the Swing Essentials web site.  Pretty cool, I must say.  I decided it might be easier to have a professional tell me what I was doing wrong online rather than being humiliated by the Pro at the local driving range.|:::|My biggest problem was my posture, squaring of the shoulders, sway, swing speed, and follow through, in other words I should have given up golf years ago.  The only redeeming quality was the top and bottom of my swing looked great. I'm glad I bought that new Nike hat and golf shoes this year.  I now have a better idea of what all my golf partners see when I tee off.  And I thought Mortie's swing was bad!  Before next season, I'll need to lose the fat and hit the Mega Million, I still have my eye on those Pings.  Man's got to have dreams...Let's go bowling Dude.|:::|The Big Toe (TBT)",
    },
    {
        id: '7',
        date: '2015-10-20',
        title: 'No Dress Code',
        body:
            "I am fortunate enough to still have a few BFF's amongst the living and we get together every October to play golf and catch up on life's surprises. I won't tell you where because it is a well guarded secret, but it's near Tennessee. These annual events give us a chance to relax, play a couple of rounds of golf, play poker and get wasted like in the old days. Don't worry, Frankie, we won't tell your wives where you were this weekend. What more could a bunch of old goats ask for.|:::|This year I noticed a few things. My golf game still sucks, I'm old and fat, and when the hell did hair start growing out of my ears? Who cares, as long as I can still get on in regulation. Hey Hugo, can you make me another big beefy cocktail. The back I threw out on 9 doesn't hurt that much and I'll call the doctor on Monday.|:::|Golf in the fall is awesome. The foliage and weather is easier on my self induced headaches. I am so glad the golf course is just down the road, \"Stop the car, I think I'm going to hurl\". This year we all agreed we'd play the same course because there's no dress code. Some of us only have blue jeans and my one and only golf shirt is in the dirty clothes. You know Mortie, you ought to patch those gabardines or you're going to lose that billfold\".|:::|We always stop after 18 at the corner gas station to buy our scratch and sniff lottery tickets. You'd think one of us would have hit the big one by now, I have big plans. Even Bernie had a hole in one a couple of years ago. Jesus, can't I count on you people? Maybe next year.|:::|The Big Toe (TBT)\r\n",
    },
    {
        id: '6',
        date: '2015-09-15',
        title: "You're Killing Me Mortie!",
        body:
            "Whats wrong with all golf courses? They do nothing to speed up play. That Marshall that just blew by us, isn't he supposed to tell slow players to move it along? I've been golfing a long time but have yet to see one of them say a word to anybody about slow play. It's nice that they wave sometimes as they drive by though, makes me feel that I won't be asked to leave the course. Some golf courses have made an attempt by having GPS in the newer carts pop up a message saying you're so many minutes behind schedule. We always ignore it because we can't go any faster, who let a fivesome out on a weekend and who plays on weekends? Most people I know say four hours is acceptable for a round of golf. Where I golf, thats after nine. Four hours is half a day and when you think about it that's ludicrous, especially with my golf scores. But here I sit, waiting? I take that back, here I stand because there's no place to sit, where's a bathroom?|:::|If I was the club pro I'd hire my buddy, Hugo. He's a huge beefy guy that hates slow players and never waved to anybody in his life. He's the guy who hits into golfers thinking it will speed up the game. Makes me a little uncomfortable but so far no blows have been thrown. Personally I think slow play besides looking for lost balls, is caused by your average player thinking they can read a green.  Give me a break! There ought to be a rule that unless your a pro you get one look and finish putting in less than 2 minutes.|:::|Ya know, that butt wiggle you do on the tee is a bit excessive but your routine on the greens is really grinding on me. Have I seen you birdie a hole this year, why do I even play golf with you?  Let me ask you a question, when you were learning to play golf, who taught you to wiggle your butt, toes, or whatever you do when addressing the ball? I've taken a few lessons in my time and can't recall the pro telling me I need to wiggle my ass a little more to get more distance and correct my slice. You're killing me Mortie!|:::|Let's face it, there's not much we can to do about slow play. We could ask the pro to hire another Marshall to move things along, and, \"Hey!   Get off that cell phone and putt for God's sake\".  Note to self: Take a video of your buddy and show him how ridiculous he looks when teeing off, you'll have plenty of time.|:::|The Big Toe (TBT)",
    },
    {
        id: '5',
        date: '2015-08-09',
        title: 'My First Live PGA Tournament',
        body:
            "I'm ashamed to say I've never attended a live PGA Tournament in my life, but I was fortunate enough to score a free Quicken Loan National Golf Tournament ticket this weekend. It was a beautiful day and my wife and I decided to give it a shot and see what we've been missing all these years. Let me say I was pleasantly surprised. My hats off to the tournament planners. We simply followed well marked golf signs and parked a short distance from the golf course. After parking we casually followed the crowd to the bus loading zone, where two huge security dudes checked everybody waiting in line to make sure we weren't packing. No purses, bottles, coolers or oversized lawn chairs. Phone, keys, and wallets with lots of cash is best. We quickly boarded a new air conditioned bus and were dropped off 20 feet from the entrance to the tournament, wow! Several large air conditioned tents were set up at the entrance where we picked up my free ticket at Will Call and my wife's ticket from some guy selling half price near the entrance.|:::|Soon we were watching Ernie Els drop one in at the 5th hole. He looks just like he does on my big screen, purple pants and all! Most of the greens and fairways were crowded at times but some were not, couldn't get near Tiger. What worked for us was to find a shady spot close to a green or tee box and wait for the golfers we wanted to see come through. I didn't realize how short we both were until this weekend, \"hey you in front, can you move over just a touch?\" Apparently it's forbidden to take a picture of the pros with your iphone, but if you do have to use your phone in an emergency, just turn your volume down and text your buddies to bring you a dog and a cold one to the hole near all the Porta Potties.|:::|What really blew me away this weekend was how slow the pros play. Honest to God, I couldn't believe the routines these guys go through once they get to the greens. I'd bet the average time for two of the pros to putt out was about 20-25 minutes a hole. Pure torture no matter how good that 30 footer was. I think I nodded off on number 9. I must say though, it was great to stroll around the course on a beautiful day and watch all the pros convince me that I should give up golf. Three or four hours was good for us and we decided to finish watching the tournament at home. For those who stayed, good on ya. \"Freeze, Ricky is putting and put that phone away!\"|:::|-The Big Toe (TBT)\r\n",
    },
    {
        id: '4',
        date: '2015-07-06',
        title: 'The Pro Shop',
        body:
            "What was the last item you purchased at your local golf pro shop besides a sleeve of Pro V1's or maybe a new golf glove? I usually buy plenty of golf balls at the pro shop just before tee time. I've been known to lose a few on every hole. If I can't find my golf ball in less than ten seconds I drop and play on. My golf partners think I cheat, but I haven't thrown a hammy or sprained an ankle in a long time...don't count that! I'll only go into the tall weeds or trees when there are no bathrooms around. Dude, beer me... and stay clear of that poison oak.|:::|I often look for things in pro shops that might improve my golf game or look good on me, however, because I need my money for retirement I shop Amazon. If you have unlimited funds and do shop at a pro shop a \"Platinum Credit Card\" will never be refused. I can't believe the mark up; did I mention green fees? Have you noticed that most pro shops carry a lot of ugly colored, striped shirts that make everybody look 10 years older? I tend to think that pro shop employees who order the clothing are all color blind with big feet. The only thing my golf buddies and I buy these days are the ball caps, usually located in the corner above the over priced size 14 Foot Joys. I've seen a few women buy visors and a few accessories in pro shops but that's about it. Is that because the bathrooms double as fitting rooms, and where's the guy with the key to the Oakley sunglass display?|:::|There are certain times when you have to suck it up. If I forget to wear a shirt with a collar, good luck on finding something you like in your size. Quick tip - always carry a golf shirt in your golf bag. You'll save yourself at least the price of a new golf shirt and besides, purple won't work with the checkered shorts and black socks. I've had to purchase a jacket or hoodie when the weather turned cold but I gave that XL jacket with the logo to my son a few years later. Hey! I only wore it once. Note to self: Buy a new jacket at Dick's and put in your golf bag.|:::|I think golf shop management should keep the hats, a few jackets and dump the overpriced clothing and stick to golf clubs. Leave the clothing to those who know what they're doing. Looks good on you though!|:::|If you decide to buy golf clubs from a pro shop and have them custom fit, it's actually a pretty good deal and might even take a few strokes off your game. Good luck and don't forget the cigars. My new Pings are on order.|:::|The Big Toe (TBT)",
    },
    {
        id: '3',
        date: '2015-06-10',
        title: "What's Wrong With Golf Courses",
        body:
            "Question, what is the biggest reason serious golfers rush a golf shot, lose all concentration, and take the chance of losing a match?  Answer, they have to pee big time.  What am I doing in the cart? Did I putt out? I don't care, hurry up you guys!|:::|In the interest of dwindling golf participation, loss of interest, revenue, and corporate takeovers, I urge all golf course management and golf professionals everywhere to make the game of golf more enjoyable by investing in more golf course bathrooms.  Everyone would agree that one or two bathrooms is totally inadequate and always has been.   No need to mention, the majority of course bathrooms always need cleaning, toilet paper, or outright demolition. Whats wrong with Nicklaus, Fazzio, and Robert Trent Jones? You think they could design a course with us geezers in mind. If my bladder doesn't start working by next week their kids are out 150 bucks. Jack, Tom, Robert, rent some Porta-Potties for God's sake.|:::|I heard a story the other day about a guy charged with indecent exposure on a golf course and had to register as a sex offender.  I'm not sure if the story is true but I'm thinking about buying a box of \"depends\" and limiting my beer intake  the next time I play.  I even noticed some golf courses are locking their bathroom doors.  Whats up with that?|:::|I used to finish 18 holes with only one bathroom break but because I'm getting old, I'm wasting way too many good shots, \"gotta go, gotta go\".  Forget those pills they advertise on TV, they don't work.  I try and hook or slice close to large bushes or trees to help shield myself from from the vacant fairway homes and golfers before taking a wihiz. Truth be told, I've even taken a leak once in the middle of a fairway.  I'm not proud of it but it was an emergency. There were no bushes and I was one up with one hole to go.|:::|I'm sure you all have seen Arnold Palmer's commercial about slow golf play, telling Clint Eastwood \"Come on while we're still young\".  Not true, Arnold just had to pee and the bathroom on the 9th hole was locked.|:::|The Big Toe (TBT)",
    },
    {
        id: '2',
        date: '2015-05-12',
        title: 'Las Vegas Golf Tips',
        body:
            "Should you choose Las Vegas as your next golf destination, I've listed a few tips that might make your Vegas trip a little more enjoyable. My first tip is to leave your golf clubs at home. \"What??\" you say, \"I can't golf without my own clubs!\"  I can relate to that, but you do know most good courses have rentals. You might even get to rent those Pings you talk about every year.  Truth be told, I'm just lazy and don't want to throw out my back again carrying my heavy golf bag through the airport. I can't tell you how many times I've left my cell phone in my golf bag and I hate waiting in the baggage area wondering where the hell my clubs went.   Don't forget to pack your golf shoes, nobody wants to hear why you couldn't get off the tee because you were in flip-flops.|:::|If you're too cheap to rent clubs then take a driving range golf bag in your carry-on and share clubs with your BFF.  Just make sure you don't get stuck sharing a golf cart and clubs with the new guy.  If this should happen, It's a sure bet you'll ruin his game and don't expect any offers to buy you a cold one when the cart girl comes by.  I, on the other hand, need only to borrow the 3 wood, Lob wedge, and a putter, so I've got that going for me, which is nice.|:::|When in Vegas you need to keep your Casino and your golf play separate.  What I mean is if you party the night before, you'll need to function somewhat at the golf course the next day.  It's a good idea to make tee times after lunch and give yourself time to recover from whatever you think happened the night before. Don't worry, we'll wait until you leave town before we talk about you. What happens in Vegas doesn't really stay in Vegas.|:::|Once you get to the first tee you're on your own; however, there is one tip I've been using for years.  It's called (insert your name)'s rule 101 which allows your foursome to tee off first. Your buddies behind you are probably in worse shape than you so they won't mind the wait.  If you're lucky, you might even make a few of those six inch putts you're famous for missing.  You'll  need an edge to win more than a few holes to re-coup some cash to pay off your marker at the Casino.|:::|Make sure you stay at a nice hotel close to the golf courses you want to play.  Who wants to spend time in the back seat of a taxi cab with a faulty air conditioner in the middle of the desert; you're already dehydrated.|:::|Finally, If you're not having any fun like you imagined, turn your clubs in after 9 and cab it back to the hotel.  Change into that ridiculous looking swimsuit you bought \"on sale\" at Big Lots and stroll down to the pool area. If you can find a chaise lounge you can fit on, order a large Bahama Mama, a plate of nachos, and take a nap.  Nobody is going to miss you anyway, you cheap bastard.   Yo Eleven.|:::|The Big Toe (TBT)",
    },
    {
        id: '1',
        date: '2015-04-02',
        title: 'First Trip to the Driving Range',
        body:
            'Yesterday I finally left my comfort zone and drove to the local driving range in and attempt to assess my golf game.|:::|Did I enjoy myself?  Not really but I?m on a quest to get back in the game, a promise is a promise, who said that?  I can?t remember how long It used to take to hit a large bucket of golf balls, but my hands hurt, blister coming, and my body is telling me to slow the f*** down you idiot!|:::|Ok my first ten drives sucked, I must be swinging too hard, let me try my five iron.  Damn, I think I cracked a rib, give me the wedge. What am I doing wrong, maybe I should have worn my other hat. Damn, it?s cold out here today, I should have brought my windbreaker, wait I never had a windbreaker. And who wants to golf in the cold weather, cold you call 50 degrees cold, you?re such a wuss?  If it was a bit warmer perhaps I wouldn?t notice the stiffness in my left shoulder, right knee and lower back.|:::|Ok, maybe with the Spring thaw I can hit off the grass, I never liked those green mats and the rubber tees, no wonder my favorite driver doesn?t work.  Ok, ok, maybe a few more trips to the driving range are in order.  I?ll work out the stiffness and with some minor back surgery I could be on in regulation. Quit whining... The year has just begun|:::|-T.B.T.',
    },
];
