name: Code Checks & Build

on:
    workflow_call:
    pull_request:
        branches: ['dev', 'master']

jobs:
    check-and-build:
        name: Run Code Checks and Build
        runs-on: ubuntu-latest
        environment: ${{ github.ref_name == 'master' && 'production' || 'staging' }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: 10.x

            - name: Set up NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: 'pnpm'
                  cache-dependency-path: ./pnpm-lock.yaml

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Run Prettier
              run: pnpm run prettier:check

            - name: Run ESLint
              run: pnpm run lint

            - name: Replace Port in .htaccess
              run: |
                  sed -i 's/{{PORT}}/${{ vars.API_PORT }}/g' ./public/.htaccess

            - name: Run Build
              env:
                  VITE_PAYPAL_MODE: '${{ vars.PAYPAL_MODE }}'
                  VITE_PAYPAL_CLIENT_ID_SANDBOX: '${{ secrets.PAYPAL_CLIENT_ID_SANDBOX }}'
                  VITE_PAYPAL_CLIENT_ID_PROD: '${{ secrets.PAYPAL_CLIENT_ID_PROD }}'
                  VITE_BASE_URL: '${{ vars.BASE_URL }}'
                  VITE_BASE_API: '${{ vars.BASE_API }}'
              run: pnpm run build

            - name: Store Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ui-build
                  path: ./dist
                  retention-days: 1
