name: Deploy

on:
    workflow_dispatch:

jobs:
    check-and-build:
        name: Run Code Checks and Build
        uses: ./.github/workflows/code-checks.yml

    deploy:
        name: Deploy to Environment
        needs: check-and-build
        runs-on: ubuntu-latest
        environment: ${{ github.ref_name == 'master' && 'production' || 'staging' }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Retrieve Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: ui-build
                  path: ./dist

            - name: Debug Environment Variables
              run: |
                  echo "VITE_PAYPAL_MODE=${{ vars.PAYPAL_MODE }}"
                  echo "VITE_PAYPAL_CLIENT_ID_SANDBOX=${{ secrets.PAYPAL_CLIENT_ID_SANDBOX }}"
                  echo "VITE_PAYPAL_CLIENT_ID_PROD=${{ secrets.PAYPAL_CLIENT_ID_PROD }}"
                  echo "VITE_BASE_URL=${{ vars.BASE_URL }}"
                  echo "VITE_BASE_API=${{ vars.BASE_API }}"

            - name: Deploy via FTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.FTP_HOST }}
                  username: ${{ secrets.FTP_USER }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./dist/
                  server-dir: ${{ vars.DEPLOY_LOCATION }}
